# Generated by Django 3.1.6 on 2021-03-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210302_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing',
            new_name='title',
        ),
    ]
