# Generated by Django 3.1.6 on 2021-03-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210302_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='open_status',
            field=models.BooleanField(default=True),
        ),
    ]
