# Generated by Django 3.1.6 on 2021-03-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210303_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder_id',
            new_name='bidder',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
